import time
import pandas as pd
import matplotlib.pyplot as plt
from pytrends.request import TrendReq

# ------------------------------
# 設定
# ------------------------------
KEYWORDS = ["Bitcoin", "Ethereum", "NFT"]

# GitHub Actions 対策: User-Agent を指定してブラウザっぽくする
pytrends = TrendReq(
    hl="en-US",
    tz=360,
    requests_args={
        "headers": {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/91.0.4472.124 Safari/537.36"
            )
        }
    },
)

# ------------------------------
# データ取得（リトライ付き）
# ------------------------------
for attempt in range(3):
    try:
        pytrends.build_payload(KEYWORDS, timeframe="today 6-m")
        data = pytrends.interest_over_time()
        if not data.empty:
            break
    except Exception as e:
        print(f"Attempt {attempt+1} failed: {e}")
        time.sleep(5)
else:
    raise RuntimeError("Google Trends request failed after 3 attempts")

# ------------------------------
# グラフ作成
# ------------------------------
plt.figure(figsize=(10, 5))
for kw in KEYWORDS:
    plt.plot(data.index, data[kw], label=kw)

plt.title("Google Trends (Last 6 months)")
plt.xlabel("Date")
plt.ylabel("Interest")
plt.legend()
plt.tight_layout()

# 出力ファイル
plt.savefig("trends.png")
print("✅ trends.png saved")
