name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # every Monday (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run macro script
        run: |
          python market_watch_macro.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macro-artifacts
          path: |
            macro_data.csv
            macro_graph.png
```0
