name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FRED macro script
        run: |
          python market_watch_macro.py

      - name: Run Google Trends script
        run: |
          python market_watch_trends.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: market-watch-artifacts
          path: |
            macro_trends.png
            macro_data.csv
            google_trends_keywords.png
            google_trends.csv
