name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"  # every Monday & Thursday 00:00 UTC -> 09:00 JST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python market_watch_auto.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: market-watch-artifacts
          path: |
            financial_*.png
            trends_*.png
            trends_*.csv
            merged_*.csv
