name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas matplotlib pytrends fredapi
          fi

      - name: Run macro script
        run: |
          python market_watch_macro.py

      - name: Run trends script
        run: |
          python trends.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: market-results
          path: |
            macro_data.csv
            macro_graph.png
            trends_data.csv
            trends_graph.png
