name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"  # every Monday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib pytrends

      - name: Run script
        run: python market_watch_auto.py

      - name: Rename result with date
        run: |
          DATE=$(date +'%Y-%m-%d')
          mv trend.png trend_${DATE}.png

      - name: Upload result graph
        uses: actions/upload-artifact@v3
        with:
          name: trend-graph
          path: trend_*.png
