name: auto_update

on:
  push:
  schedule:
    - cron: '0 0 * * 1,4'  # 毎週月曜と木曜の09:00 (UTC換算で0:00)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib pandas

      - name: Run script
        run: python market_watch_auto.py
