name: auto_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # 毎週月曜0:00 UTC（必要に応じて変更）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib pytrends pandas_datareader requests

      - name: Run script
        run: |
          python market_watch_auto.py

      - name: Package results
        run: |
          mkdir -p artifacts
          # copy files if exist
          for f in macro_graph.png macro_data.csv trends_graph.png trends_data.csv; do
            if [ -f "$f" ]; then cp "$f" artifacts/; fi
          done
          cd artifacts || exit 0
          zip -r ../market_watch_results.zip . || true
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: market-watch-artifacts
          path: |
            market_watch_results.zip
            macro_graph.png
            macro_data.csv
            trends_graph.png
            trends_data.csv
